# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: AJUG | Atlanta Java User Group
email: info@ajug.org
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: atlantajug
github_username:  devnexus
_options:
  meetup_image_path:
    uploads_dir: "/assets/img/meetups"
  sponsor_image_path:
    uploads_dir: "/assets/img/sponsors"
    width: 300
    height: 300
    resize_style: "cover"
    mime_type: "image/jpeg"
    expandable: false
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      path: "assets/img/sponsors"
    values:
      sponsor: true
# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
