source: ''
paths:
  static: ''
  uploads: uploads
  uploads_use_relative_path: false
  dam_uploads: ''
  dam_static: ''
  data: _data
  collections: _posts
  layouts: _layouts
collections_config:
  posts:
    path: _posts
    name: Events
    icon: event_available
    disable_url: true
    description: 'group meetups and events.'
    
    # How the list looks in the CloudCannon UI
    preview:
      text:
        - key: title
      subtext:
        - key: date
      image:
        - key: image

    # This defines the file naming convention when creating a new post
    create:
      path: "[relative_base_path]/{date|year}-{date|month}-{date|day}-{title|slugify}.[ext]"

    # Define the actual editor fields here
    _inputs:
      title:
        type: text
        label: Event Title
        comment: "Required: The name of the event."
        instance_values:
          value: "New Event"
      
      date:
        type: date
        label: Event Date
        comment: "Select the date for this event (can be in the future)."
        options:
          format: "YYYY-MM-DD"
      
      registration:
        type: url
        placeholder: https://luma.com/ajug
      
      image:
        type: image
        options:
          paths:
            uploads: /assets/img/meetups
          width: 1600
          height: 1200
          resize_style: cover
          allowed_sources:
            - uploads
            - existing
            - url
data_config: {}
collection_groups:
  - heading: Pages
    collections:
      - pages
  - heading: Content
    collections:
      - posts
_enabled_editors: null
_inputs:
  date:
    type: date
  time:
    type: text
  title:
    type: text
  link:
    type: url
  image:
    type: image
    options:
      uploads_dir: /assets/img
  meetup_image_path:
    type: image
    uploads_dir: /assets/img/meetups
  meetup_link:
    type: url
  categories:
    type: multiselect
    options:
      allow_create: true
  tags:
    type: multiselect
    options:
      allow_create: true
  meetup_image_path:
    type: image
    options:
      uploads_dir: /assets/img/meetups
  sponsor_image_path:
    type: image
    options:
      uploads_dir: /assets/img/sponsors
      width: 300
      height: 300
      resize_style: cover
      mime_type: image/jpeg
      expandable: false
_select_data:
  sass:
    sass_dir: _sass
_editables: {}
commit_templates: []
base_url: ''
editor: null
source_editor: null
timezone: Etc/UTC
